export const RATES = { CNY: 12.58, USD: 89.69, date: '1/9/2024' }

export const CARS = {
  Lotus: {
    submodels: {
      Eletre: {
        trims: ['S+', 'R+', 'S'],
        images: [
          '/colors/lotus-eletre-front1.jpg',
          '/colors/lotus-eletre-side1.jpg',
          '/colors/lotus-eletre-rear1.jpg',
          '/colors/lotus-eletre-front2.jpg',
          '/colors/lotus-eletre-side2.jpg',
          '/colors/lotus-eletre-rear2.jpg',
        ],
        invoice: { carPrice: 792480, deliverySochi: 19000, total: 826480 },
        customs: 18000,
        deliveryMoscow: 1500,
        commission: 1500,
        epts: 1100,
        bodyColors: [
          { name: 'Solar Yellow',    hex: '#D4B800', price: 0,
            images: ['/colors/lotus-eletre-front1.jpg', '/colors/lotus-eletre-side1.jpg', '/colors/lotus-eletre-rear1.jpg', '/colors/lotus-eletre-front2.jpg'] },
          { name: 'Galoway Green',   hex: '#017B4C', price: 0,
            images: ['/colors/green.jpg', '/colors/green2.jpg', '/colors/lotus-eletre-side2.jpg'] },
          { name: 'Stellar Black',   hex: '#0D0D0D', price: 0,
            images: ['/colors/black.jpg', '/colors/lotus-eletre-rear2.jpg', '/colors/lotus-eletre-side2.jpg'] },
          { name: 'Blossom Gray',    hex: '#C8C4BE', price: 0,
            images: ['/colors/lotus-eletre-side1.jpg', '/colors/lotus-eletre-front2.jpg', '/colors/lotus-eletre-rear1.jpg'],
            filter: 'grayscale(60%) brightness(1.1)' },
          { name: 'Kaimu Grey',      hex: '#7A7A78', price: 0,
            images: ['/colors/lotus-eletre-side2.jpg', '/colors/lotus-eletre-rear2.jpg'],
            filter: 'grayscale(80%) brightness(0.95)' },
          { name: 'Dust Storm',      hex: '#C2A882', price: 0,
            images: ['/colors/lotus-eletre-front2.jpg', '/colors/lotus-eletre-side1.jpg'],
            filter: 'sepia(30%) saturate(0.8)' },
        ],
        interiorColors: [
          { name: 'Тёмно-синий',  hex: '#2A3A5C', price: 0,
            images: ['/colors/lotus-eletre-inter1.jpg', '/colors/lotus-eletre-inter3.jpg'] },
          { name: 'Чёрный',       hex: '#1A1A1A', price: 0,
            images: ['/colors/lotus-eletre-inter4.jpg', '/colors/lotus-eletre-inter5.jpg'] },
          { name: 'Жёлтый',       hex: '#C8A000', price: 0,
            images: ['/colors/lotus-eletre-inter1.jpg', '/colors/lotus-eletre-inter6.jpg'] },
          { name: 'Мятный',       hex: '#78C8A0', price: 0,
            images: ['/colors/lotus-eletre-inter6.jpg', '/colors/lotus-eletre-inter3.jpg'] },
          { name: 'Кремовый',     hex: '#E8DCC8', price: 0,
            images: ['/colors/lotus-eletre-inter7.jpg', '/colors/lotus-eletre-inter5.jpg'] },
          { name: 'Чёрно-белый',  hex: '#C8C0B8', price: 0,
            images: ['/colors/lotus-eletre-inter3.jpg', '/colors/lotus-eletre-inter7.jpg'] },
        ],
        wheels: [
          { name: '20" Black Wheels', spokes: 5,  rimColor: '#1A1A1A', spokeColor: '#444', price: 0,
            previewImg: '/colors/lotus-eletre-side1.jpg' },
          { name: '21" Sport',        spokes: 10, rimColor: '#222',    spokeColor: '#555', price: 2000,
            previewImg: '/colors/lotus-eletre-side2.jpg' },
          { name: '22" Diamond',      spokes: 7,  rimColor: '#B8B8B8', spokeColor: '#DDD', price: 4000,
            previewImg: '/colors/lotus-eletre-side1.jpg' },
          { name: '20" Silver',       spokes: 5,  rimColor: '#909090', spokeColor: '#BBB', price: 1000,
            previewImg: '/colors/lotus-eletre-side2.jpg' },
        ],
        caliperColors: [
          { name: 'Зелёный',     hex: '#1A9141', price: 0 },
          { name: 'Красный',     hex: '#C0392B', price: 0 },
          { name: 'Серебристый', hex: '#B8B8B8', price: 0 },
          { name: 'Жёлтый',     hex: '#D4A800', price: 0 },
          { name: 'Серый',       hex: '#888888', price: 0 },
        ],
        extras: [
          { name: 'Спортивные шины с повышенной износоустойчивостью', price: 5000 },
          { name: 'Внешний глянцевый черный комплект', price: 0 },
          { name: 'Комплект активного управления Lotus (Активное рулевое управление задним колесом и система крена)', price: 0 },
          { name: 'Активный аэродинамический комплект Lotus', price: 0 },
          { name: 'Умный панорамный навес PDLC (10 режимов светопропускания)', price: 0 },
          { name: 'Интеллектуальное вождение Lotus (Адаптивный круиз и полноценная система предупреждения)', price: 0 },
          { name: 'Акустическая система KEF Acoustic Benchmark (23 динамика, 2160 Вт)', price: 0 },
          { name: 'Четырехместный салон', price: 30000 },
        ],
        specs: [
          {
            group: 'Основные',
            items: [
              { label: 'Батарея',                    value: '112 кВт·ч' },
              { label: 'Разгон от 0 до 100 км/ч',   value: '4.5 сек' },
              { label: 'Максимальная скорость',       value: '258 км/ч' },
              { label: 'Запас хода',                 value: '580 км (по циклу WLTP)' },
              { label: 'Мощность двигателя',         value: '603 л.с.' },
              { label: 'Крутящий момент',             value: '— Н·м' },
              { label: 'Привод',                     value: 'Полный (AWD)' },
              { label: 'Количество мест',             value: '5 взрослых' },
              { label: 'Вес',                        value: '— кг' },
              { label: 'Длина',                      value: '5 103 мм' },
              { label: 'Ширина',                     value: '2 019 мм' },
              { label: 'Высота',                     value: '1 630 мм' },
              { label: 'Объём грузового пространства', value: '611 л' },
            ],
          },
          {
            group: 'Дополнительно',
            items: [
              { label: 'Мощность зарядки (AC)',      value: '22 кВт' },
              { label: 'Мощность зарядки (DC)',      value: '350 кВт' },
              { label: 'Зарядка 10–80% (DC)',        value: '20 мин' },
              { label: 'Колёсная база',              value: '2 780 мм' },
              { label: 'Клиренс',                   value: '136–206 мм' },
              { label: 'Объём переднего багажника',  value: '46 л' },
              { label: 'Тип подвески',              value: 'Активная многорычажная' },
              { label: 'Тормоза передние',          value: '420 мм, 6-поршн.' },
              { label: 'Тормоза задние',            value: '390 мм, 4-поршн.' },
              { label: 'Гарантия на батарею',       value: '8 лет / 160 000 км' },
            ],
          },
        ],
        description: {
          title: 'Lotus Eletre: Эксклюзивный Спортивный Электрический Шедевр',
          text: 'Автомобиль базово укомплектован системами крена и активного управления задним колесом, активным аэродинамическим комплектом, умным панорамным навесом PDLC с 10-ю режимами светопропускания и адаптивным круиз контролем с функцией предупреждения. За дополнительную плату в максимальной версии также включаются опции: электрический фаркоп, мультимедийные внешние зеркала заднего вида, акустическая система KEF Acoustic Benchmark с 23 мя динамиками пиковой мощностью 2160 Вт, системой умного вождения Lotus Premium с двумя режимами автопилота и «умной» парковкой. Предлагаем адекватную цену на новейшие продукты китайского автопрома, делаем их доступными для широкого круга автолюбителей в России.',
        },
        mediaBlocks: [
          {
            src: '/lotus-multimedia.jpg',
            caption: 'Мультимедиа Lotus Eletre',
          },
          {
            src: '/lotus-chassis.jpg',
            caption: 'Технологии MIM (инжекционное литьё деталей)',
            stats: ['1323', '1108', '5.3', '3.5'],
          },
          {
            src: '/lotus-exterior.jpg',
            caption: 'Дизайн Lotus Eletre',
            stats: ['0.236 Cd', '4912 мм', '2019 мм', '1636 мм'],
          },
          {
            src: '/lixiang-family.jpg',
            caption: 'Комфорт и пространство салона',
          },
          {
            src: '/lixiang-hud.jpg',
            caption: 'Интеллектуальная система вождения',
            stats: ['ADAS L3', 'HUD AR', '300 м', '24 сенсора'],
          },
          {
            src: '/lixiang-charging.jpg',
            caption: 'Беспроводная зарядка двух устройств одновременно',
          },
        ],
      },
      Emeya: {
        trims: ['R', 'S'],
        images: [
          '/car1-5/Property 1=Black.jpg',
          '/car1-5/Property 1=Grey.jpg',
          '/car1-5/Property 1=White.jpg',
        ],
        invoice: { carPrice: 680000, deliverySochi: 19000, total: 714000 },
        customs: 16000,
        deliveryMoscow: 1500,
        commission: 1500,
        epts: 1100,
        bodyColors: [
          { name: 'Чёрный',    hex: '#1A1A1A', price: 0 },
          { name: 'Серый',     hex: '#A8ADB0', price: 0 },
          { name: 'Белый',     hex: '#F0F0F0', price: 0 },
          { name: 'Синий',     hex: '#1A3060', price: 0 },
          { name: 'Красный',   hex: '#A01818', price: 0 },
        ],
        interiorColors: [
          { name: 'Чёрный',   hex: '#1A1A1A', price: 0 },
          { name: 'Бежевый',  hex: '#D8C8A8', price: 0 },
          { name: 'Серый',    hex: '#808080', price: 0 },
          { name: 'Коричневый', hex: '#6B4226', price: 0 },
        ],
        wheels: [
          { name: '20" Standard', spokes: 5, rimColor: '#1A1A1A', spokeColor: '#444', price: 0 },
          { name: '21" Sport',    spokes: 8, rimColor: '#222',    spokeColor: '#555', price: 2000 },
        ],
        caliperColors: [
          { name: 'Чёрный',  hex: '#1A1A1A', price: 0 },
          { name: 'Красный', hex: '#C0392B', price: 0 },
          { name: 'Серый',   hex: '#888888', price: 0 },
        ],
      },
    },
  },
}
